## numpy.array 基础

In [1]:
import numpy as np

In [2]:
np.__version__

'1.15.1'

### Python List 的特点

In [3]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
L[5]

5

In [5]:
L[5] = 100
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

In [6]:
L[5] = "Machine Learning"
L

[0, 1, 2, 3, 4, 'Machine Learning', 6, 7, 8, 9]

In [7]:
import array

In [8]:
arr = array.array("i", [i for i in range(10)])

In [9]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr[5]

5

In [11]:
arr[5] = 100

In [12]:
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

In [13]:
arr[5] = "Machine Learning"

TypeError: an integer is required (got type str)

### numpy.array

In [14]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
nparr[5]

5

In [17]:
nparr[5] = 100
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [18]:
nparr[5] = "Machine Learning"

ValueError: invalid literal for int() with base 10: 'Machine Learning'

In [19]:
nparr.dtype

dtype('int32')

In [20]:
nparr[5] = 5.0
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
nparr[3] = 3.14
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
nparr2 = np.array([1, 2, 3.0])
nparr2

array([1., 2., 3.])

In [23]:
nparr2.dtype

dtype('float64')

### 其他创建 numpy.array 的方法

In [24]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
np.zeros(10).dtype

dtype('float64')

In [27]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
np.zeros(shape=(3, 5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [30]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
np.full((3, 5), 666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [32]:
np.full((3, 5), 666.0)

array([[666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.]])

In [33]:
np.full(fill_value=666.0, shape=10)

array([666., 666., 666., 666., 666., 666., 666., 666., 666., 666.])

### arange

In [34]:
[i for i in range(0, 20, 2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [35]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [36]:
[i for i in range(0, 20, 0.2)]

TypeError: 'float' object cannot be interpreted as an integer

In [38]:
np.arange(0, 1, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [39]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### linspace

In [41]:
np.linspace(0, 20, 10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [42]:
np.linspace(0, 20, 11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

### random

In [43]:
np.random.randint(0, 10)

6

In [47]:
np.random.randint(0, 10, size=10)

array([3, 3, 8, 5, 1, 6, 6, 8, 5, 2])

In [49]:
np.random.randint(0, 10, size=(3, 5))

array([[8, 1, 0, 3, 8],
       [3, 1, 1, 6, 5],
       [6, 3, 2, 9, 3]])

In [50]:
np.random.randint(0, 10, size=(3, 5))

array([[6, 4, 4, 8, 9],
       [5, 5, 0, 7, 6],
       [3, 6, 1, 6, 4]])

In [51]:
np.random.seed(666)

In [52]:
np.random.randint(0, 10, size=(3, 5))

array([[2, 6, 9, 4, 3],
       [1, 0, 8, 7, 5],
       [2, 5, 5, 4, 8]])

In [54]:
np.random.seed(666)

In [55]:
np.random.randint(0, 10, size=(3, 5))

array([[2, 6, 9, 4, 3],
       [1, 0, 8, 7, 5],
       [2, 5, 5, 4, 8]])

In [56]:
np.random.random()

0.7315955468480113

In [57]:
np.random.random(10)

array([0.8578588 , 0.76741234, 0.95323137, 0.29097383, 0.84778197,
       0.3497619 , 0.92389692, 0.29489453, 0.52438061, 0.94253896])

In [59]:
np.random.random((3, 5))

array([[0.07473949, 0.27646251, 0.4675855 , 0.31581532, 0.39016259],
       [0.26832981, 0.75366384, 0.66673747, 0.87287954, 0.52109719],
       [0.75020425, 0.32940234, 0.29130197, 0.00103619, 0.6361797 ]])

In [63]:
np.random.normal(size=(3, 5))

array([[ 1.23174866, -0.91360034, -0.27084407,  1.42024914, -0.98226439],
       [ 0.80976498,  1.85205227,  1.67819021, -0.98076924,  0.47031082],
       [ 0.18226991, -0.84388249,  0.20996833,  0.22958666,  0.26307642]])

In [69]:
np.random.normal?

In [66]:
np.random?