## numpy.array 基础

In [59]:
import numpy as np

In [60]:
np.__version__

'1.15.1'

### Python List 的特点

In [61]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [62]:
L[5]

5

In [63]:
L[5] = 100
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

In [64]:
L[5] = "Machine Learning"
L

[0, 1, 2, 3, 4, 'Machine Learning', 6, 7, 8, 9]

In [65]:
import array

In [66]:
arr = array.array("i", [i for i in range(10)])

In [67]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
arr[5]

5

In [69]:
arr[5] = 100

In [70]:
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

In [71]:
arr[5] = "Machine Learning"

TypeError: an integer is required (got type str)

### numpy.array

In [72]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
nparr[5]

5

In [74]:
nparr[5] = 100
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [75]:
nparr[5] = "Machine Learning"

ValueError: invalid literal for int() with base 10: 'Machine Learning'

In [76]:
nparr.dtype

dtype('int32')

In [77]:
nparr[5] = 5.0
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
nparr[3] = 3.14
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
nparr2 = np.array([1, 2, 3.0])
nparr2

array([1., 2., 3.])

In [80]:
nparr2.dtype

dtype('float64')

### 其他创建 numpy.array 的方法

In [81]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [82]:
np.zeros(10).dtype

dtype('float64')

In [83]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [84]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [85]:
np.zeros(shape=(3, 5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [86]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [87]:
np.full((3, 5), 666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [88]:
np.full((3, 5), 666.0)

array([[666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.]])

In [89]:
np.full(fill_value=666.0, shape=10)

array([666., 666., 666., 666., 666., 666., 666., 666., 666., 666.])

### arange

In [90]:
[i for i in range(0, 20, 2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [91]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [96]:
[i for i in range(0, 20, 0.2)]

TypeError: 'float' object cannot be interpreted as an integer

In [93]:
np.arange(0, 1, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [94]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### linspace

In [97]:
np.linspace(0, 20, 10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [98]:
np.linspace(0, 20, 11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

### random

In [99]:
np.random.randint(0, 10)

2

In [100]:
np.random.randint(0, 10, size=10)

array([6, 9, 4, 3, 1, 0, 8, 7, 5, 2])

In [101]:
np.random.randint(0, 10, size=(3, 5))

array([[5, 5, 4, 8, 4],
       [4, 0, 0, 4, 0],
       [4, 5, 7, 1, 0]])

In [102]:
np.random.randint(0, 10, size=(3, 5))

array([[0, 6, 6, 0, 3],
       [2, 9, 2, 6, 0],
       [6, 0, 9, 3, 6]])

In [103]:
np.random.seed(666)

In [104]:
np.random.randint(0, 10, size=(3, 5))

array([[2, 6, 9, 4, 3],
       [1, 0, 8, 7, 5],
       [2, 5, 5, 4, 8]])

In [105]:
np.random.seed(666)

In [106]:
np.random.randint(0, 10, size=(3, 5))

array([[2, 6, 9, 4, 3],
       [1, 0, 8, 7, 5],
       [2, 5, 5, 4, 8]])

In [107]:
np.random.random()

0.7315955468480113

In [108]:
np.random.random(10)

array([0.8578588 , 0.76741234, 0.95323137, 0.29097383, 0.84778197,
       0.3497619 , 0.92389692, 0.29489453, 0.52438061, 0.94253896])

In [109]:
np.random.random((3, 5))

array([[0.07473949, 0.27646251, 0.4675855 , 0.31581532, 0.39016259],
       [0.26832981, 0.75366384, 0.66673747, 0.87287954, 0.52109719],
       [0.75020425, 0.32940234, 0.29130197, 0.00103619, 0.6361797 ]])

In [110]:
np.random.normal(size=(3, 5))

array([[-1.56448586, -1.62879004,  1.23174866, -0.91360034, -0.27084407],
       [ 1.42024914, -0.98226439,  0.80976498,  1.85205227,  1.67819021],
       [-0.98076924,  0.47031082,  0.18226991, -0.84388249,  0.20996833]])

In [111]:
np.random.normal?

In [112]:
np.random?