## 聚合操作

In [2]:
import numpy as np
L = np.random.random(100)

In [3]:
sum(L)

49.659297280191154

In [4]:
np.sum(L)

49.659297280191154

In [5]:
big_array = np.random.random(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

98.3 ms ± 2.94 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.27 ms ± 53 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
np.min(big_array)

1.7617442769068958e-06

In [7]:
np.max(big_array)

0.9999996007494253

In [8]:
big_array.min()

1.7617442769068958e-06

In [9]:
big_array.max()

0.9999996007494253

In [10]:
big_array.sum()

500306.4972199201

In [11]:
X = np.arange(16).reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
np.sum(X)

120

In [13]:
np.sum(X, axis=0)

array([24, 28, 32, 36])

In [14]:
np.sum(X, axis=1)

array([ 6, 22, 38, 54])

In [15]:
np.prod(X)

0

In [16]:
np.prod(X + 1)

2004189184

In [17]:
np.mean(X)

7.5

In [18]:
np.median(X)

7.5

In [19]:
v = np.array([1, 1, 2, 2, 10])
np.mean(v)

3.2

In [20]:
np.median(v)

2.0

In [22]:
np.percentile(big_array, q=50)

0.5004640930233302

In [23]:
np.median(big_array)

0.5004640930233302

In [24]:
np.percentile(big_array, q=100)

0.9999996007494253

In [25]:
np.max(big_array)

0.9999996007494253

In [26]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, q=percent))

1.7617442769068958e-06
0.25022625652248764
0.5004640930233302
0.7503780584828126
0.9999996007494253


In [27]:
np.var(big_array)

0.08330481358933708

In [28]:
np.std(big_array)

0.2886257327220445

In [29]:
x = np.random.normal(0, 1, size=1000000)

In [30]:
np.mean(x)

-0.0007928586057341468

In [31]:
np.std(x)

0.9993517143713011

### 索引

In [32]:
np.min(x)

-4.8781937010324805

In [33]:
np.argmin(x)

863055

In [35]:
x[863055]

-4.8781937010324805

In [36]:
np.argmax(x)

750328

In [37]:
x[750328]

5.059898917820353

In [38]:
np.max(x)

5.059898917820353

### 排序和使用索引

In [39]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [40]:
np.random.shuffle(x)
x

array([12, 14, 10,  6, 15, 13,  1,  5,  2,  8,  9,  3, 11,  7,  4,  0])

In [41]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [42]:
x.sort()

In [43]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [44]:
X = np.random.randint(10, size=(4,4))
X

array([[6, 0, 8, 1],
       [5, 6, 0, 4],
       [9, 6, 8, 8],
       [6, 7, 1, 2]])

In [45]:
np.sort(X)

array([[0, 1, 6, 8],
       [0, 4, 5, 6],
       [6, 8, 8, 9],
       [1, 2, 6, 7]])

In [46]:
np.sort(X, axis=1)

array([[0, 1, 6, 8],
       [0, 4, 5, 6],
       [6, 8, 8, 9],
       [1, 2, 6, 7]])

In [47]:
np.sort(X, axis=0)

array([[5, 0, 0, 1],
       [6, 6, 1, 2],
       [6, 6, 8, 4],
       [9, 7, 8, 8]])

In [48]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [49]:
np.random.shuffle(x)
x

array([10,  1, 12,  3, 14,  2,  6, 11,  8, 15,  0,  5,  4, 13,  9,  7])

In [50]:
np.argsort(x)

array([10,  1,  5,  3, 12, 11,  6, 15,  8, 14,  0,  7,  2, 13,  4,  9],
      dtype=int64)

In [51]:
np.partition(x, 3)

array([ 1,  0,  2,  3,  4,  7,  6,  9,  8,  5, 10, 15, 14, 13, 12, 11])

In [52]:
np.argpartition(x, 3)

array([ 1, 10,  5,  3, 12, 15,  6, 14,  8, 11,  0,  9,  4, 13,  2,  7],
      dtype=int64)

In [53]:
X

array([[6, 0, 8, 1],
       [5, 6, 0, 4],
       [9, 6, 8, 8],
       [6, 7, 1, 2]])

In [54]:
np.argsort(X, axis=1)

array([[1, 3, 0, 2],
       [2, 3, 0, 1],
       [1, 2, 3, 0],
       [2, 3, 0, 1]], dtype=int64)